package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1



/**
 * CRetunItems generated by hbm2java
 */
public class CRetunItems  implements java.io.Serializable {


     private Integer idCRetunItems;
     private CReturns CReturns;
     private Products products;
     private String reason;
     private Double qty;

    public CRetunItems() {
    }

	
    public CRetunItems(CReturns CReturns, Products products) {
        this.CReturns = CReturns;
        this.products = products;
    }
    public CRetunItems(CReturns CReturns, Products products, String reason, Double qty) {
       this.CReturns = CReturns;
       this.products = products;
       this.reason = reason;
       this.qty = qty;
    }
   
    public Integer getIdCRetunItems() {
        return this.idCRetunItems;
    }
    
    public void setIdCRetunItems(Integer idCRetunItems) {
        this.idCRetunItems = idCRetunItems;
    }
    public CReturns getCReturns() {
        return this.CReturns;
    }
    
    public void setCReturns(CReturns CReturns) {
        this.CReturns = CReturns;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }




}


