package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CReturns generated by hbm2java
 */
public class CReturns  implements java.io.Serializable {


     private Integer idCReturns;
     private Invoice invoice;
     private String dateTime;
     private Set CRetunItemses = new HashSet(0);

    public CReturns() {
    }

	
    public CReturns(Invoice invoice) {
        this.invoice = invoice;
    }
    public CReturns(Invoice invoice, String dateTime, Set CRetunItemses) {
       this.invoice = invoice;
       this.dateTime = dateTime;
       this.CRetunItemses = CRetunItemses;
    }
   
    public Integer getIdCReturns() {
        return this.idCReturns;
    }
    
    public void setIdCReturns(Integer idCReturns) {
        this.idCReturns = idCReturns;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }
    public Set getCRetunItemses() {
        return this.CRetunItemses;
    }
    
    public void setCRetunItemses(Set CRetunItemses) {
        this.CRetunItemses = CRetunItemses;
    }




}


