package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1



/**
 * Customerduerecords generated by hbm2java
 */
public class Customerduerecords  implements java.io.Serializable {


     private int idDueRecords;
     private CustomerDue customerDue;
     private String datetime;
     private String amount;

    public Customerduerecords() {
    }

	
    public Customerduerecords(int idDueRecords, CustomerDue customerDue) {
        this.idDueRecords = idDueRecords;
        this.customerDue = customerDue;
    }
    public Customerduerecords(int idDueRecords, CustomerDue customerDue, String datetime, String amount) {
       this.idDueRecords = idDueRecords;
       this.customerDue = customerDue;
       this.datetime = datetime;
       this.amount = amount;
    }
   
    public int getIdDueRecords() {
        return this.idDueRecords;
    }
    
    public void setIdDueRecords(int idDueRecords) {
        this.idDueRecords = idDueRecords;
    }
    public CustomerDue getCustomerDue() {
        return this.customerDue;
    }
    
    public void setCustomerDue(CustomerDue customerDue) {
        this.customerDue = customerDue;
    }
    public String getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(String datetime) {
        this.datetime = datetime;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }




}


