package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CustomerDue generated by hbm2java
 */
public class CustomerDue  implements java.io.Serializable {


     private Integer idCustomerDue;
     private Customer customer;
     private Invoice invoice;
     private Double total;
     private Double dueamount;
     private Set customerduerecordses = new HashSet(0);

    public CustomerDue() {
    }

	
    public CustomerDue(Customer customer, Invoice invoice) {
        this.customer = customer;
        this.invoice = invoice;
    }
    public CustomerDue(Customer customer, Invoice invoice, Double total, Double dueamount, Set customerduerecordses) {
       this.customer = customer;
       this.invoice = invoice;
       this.total = total;
       this.dueamount = dueamount;
       this.customerduerecordses = customerduerecordses;
    }
   
    public Integer getIdCustomerDue() {
        return this.idCustomerDue;
    }
    
    public void setIdCustomerDue(Integer idCustomerDue) {
        this.idCustomerDue = idCustomerDue;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getDueamount() {
        return this.dueamount;
    }
    
    public void setDueamount(Double dueamount) {
        this.dueamount = dueamount;
    }
    public Set getCustomerduerecordses() {
        return this.customerduerecordses;
    }
    
    public void setCustomerduerecordses(Set customerduerecordses) {
        this.customerduerecordses = customerduerecordses;
    }




}


