package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grn generated by hbm2java
 */
public class Grn  implements java.io.Serializable {


     private Integer grnId;
     private PaymentType paymentType;
     private Supplier supplier;
     private String dateTime;
     private Double totalAmount;
     private Set grnItems = new HashSet(0);
     private Set grnCredits = new HashSet(0);
     private Set supplierDues = new HashSet(0);
     private Set SReturnses = new HashSet(0);

    public Grn() {
    }

	
    public Grn(PaymentType paymentType, Supplier supplier) {
        this.paymentType = paymentType;
        this.supplier = supplier;
    }
    public Grn(PaymentType paymentType, Supplier supplier, String dateTime, Double totalAmount, Set grnItems, Set grnCredits, Set supplierDues, Set SReturnses) {
       this.paymentType = paymentType;
       this.supplier = supplier;
       this.dateTime = dateTime;
       this.totalAmount = totalAmount;
       this.grnItems = grnItems;
       this.grnCredits = grnCredits;
       this.supplierDues = supplierDues;
       this.SReturnses = SReturnses;
    }
   
    public Integer getGrnId() {
        return this.grnId;
    }
    
    public void setGrnId(Integer grnId) {
        this.grnId = grnId;
    }
    public PaymentType getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Set getGrnItems() {
        return this.grnItems;
    }
    
    public void setGrnItems(Set grnItems) {
        this.grnItems = grnItems;
    }
    public Set getGrnCredits() {
        return this.grnCredits;
    }
    
    public void setGrnCredits(Set grnCredits) {
        this.grnCredits = grnCredits;
    }
    public Set getSupplierDues() {
        return this.supplierDues;
    }
    
    public void setSupplierDues(Set supplierDues) {
        this.supplierDues = supplierDues;
    }
    public Set getSReturnses() {
        return this.SReturnses;
    }
    
    public void setSReturnses(Set SReturnses) {
        this.SReturnses = SReturnses;
    }




}


