package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1



/**
 * GrnCredit generated by hbm2java
 */
public class GrnCredit  implements java.io.Serializable {


     private Integer idGrnCredit;
     private Grn grn;
     private String dateTime;
     private Double amount;
     private Integer isPaid;

    public GrnCredit() {
    }

	
    public GrnCredit(Grn grn) {
        this.grn = grn;
    }
    public GrnCredit(Grn grn, String dateTime, Double amount, Integer isPaid) {
       this.grn = grn;
       this.dateTime = dateTime;
       this.amount = amount;
       this.isPaid = isPaid;
    }
   
    public Integer getIdGrnCredit() {
        return this.idGrnCredit;
    }
    
    public void setIdGrnCredit(Integer idGrnCredit) {
        this.idGrnCredit = idGrnCredit;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Integer getIsPaid() {
        return this.isPaid;
    }
    
    public void setIsPaid(Integer isPaid) {
        this.isPaid = isPaid;
    }




}


