package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1



/**
 * GrnItem generated by hbm2java
 */
public class GrnItem  implements java.io.Serializable {


     private Integer idGrnItem;
     private Grn grn;
     private Products products;
     private Stock stock;
     private Double unitPrice;
     private Double qty;
     private Double subTotal;
     private Double sellingPrice;

    public GrnItem() {
    }

	
    public GrnItem(Grn grn, Products products, Stock stock) {
        this.grn = grn;
        this.products = products;
        this.stock = stock;
    }
    public GrnItem(Grn grn, Products products, Stock stock, Double unitPrice, Double qty, Double subTotal, Double sellingPrice) {
       this.grn = grn;
       this.products = products;
       this.stock = stock;
       this.unitPrice = unitPrice;
       this.qty = qty;
       this.subTotal = subTotal;
       this.sellingPrice = sellingPrice;
    }
   
    public Integer getIdGrnItem() {
        return this.idGrnItem;
    }
    
    public void setIdGrnItem(Integer idGrnItem) {
        this.idGrnItem = idGrnItem;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
    }
    public Double getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(Double sellingPrice) {
        this.sellingPrice = sellingPrice;
    }




}


