package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1



/**
 * InvoiceCredit generated by hbm2java
 */
public class InvoiceCredit  implements java.io.Serializable {


     private Integer idInvoiceCredit;
     private Invoice invoice;
     private Double amount;
     private String dateTime;
     private Integer isPaid;

    public InvoiceCredit() {
    }

	
    public InvoiceCredit(Invoice invoice) {
        this.invoice = invoice;
    }
    public InvoiceCredit(Invoice invoice, Double amount, String dateTime, Integer isPaid) {
       this.invoice = invoice;
       this.amount = amount;
       this.dateTime = dateTime;
       this.isPaid = isPaid;
    }
   
    public Integer getIdInvoiceCredit() {
        return this.idInvoiceCredit;
    }
    
    public void setIdInvoiceCredit(Integer idInvoiceCredit) {
        this.idInvoiceCredit = idInvoiceCredit;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }
    public Integer getIsPaid() {
        return this.isPaid;
    }
    
    public void setIsPaid(Integer isPaid) {
        this.isPaid = isPaid;
    }




}


