package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1



/**
 * InvoiceItem generated by hbm2java
 */
public class InvoiceItem  implements java.io.Serializable {


     private Integer idInvoiceItem;
     private Invoice invoice;
     private Stock stock;
     private Double unitPrice;
     private Double qty;
     private Double subtotal;

    public InvoiceItem() {
    }

	
    public InvoiceItem(Invoice invoice, Stock stock) {
        this.invoice = invoice;
        this.stock = stock;
    }
    public InvoiceItem(Invoice invoice, Stock stock, Double unitPrice, Double qty, Double subtotal) {
       this.invoice = invoice;
       this.stock = stock;
       this.unitPrice = unitPrice;
       this.qty = qty;
       this.subtotal = subtotal;
    }
   
    public Integer getIdInvoiceItem() {
        return this.idInvoiceItem;
    }
    
    public void setIdInvoiceItem(Integer idInvoiceItem) {
        this.idInvoiceItem = idInvoiceItem;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }




}


