package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaymentType generated by hbm2java
 */
public class PaymentType  implements java.io.Serializable {


     private Integer idPaymentType;
     private String typename;
     private Integer status;
     private Set invoices = new HashSet(0);
     private Set grns = new HashSet(0);

    public PaymentType() {
    }

    public PaymentType(String typename, Integer status, Set invoices, Set grns) {
       this.typename = typename;
       this.status = status;
       this.invoices = invoices;
       this.grns = grns;
    }
   
    public Integer getIdPaymentType() {
        return this.idPaymentType;
    }
    
    public void setIdPaymentType(Integer idPaymentType) {
        this.idPaymentType = idPaymentType;
    }
    public String getTypename() {
        return this.typename;
    }
    
    public void setTypename(String typename) {
        this.typename = typename;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set grns) {
        this.grns = grns;
    }




}


