package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer idProducts;
     private Discount discount;
     private QtyType qtyType;
     private String proName;
     private String proItrmCode;
     private String description;
     private String barcode;
     private Integer status;
     private Set CRetunItemses = new HashSet(0);
     private Set SReturnItemses = new HashSet(0);
     private Set qtyloosings = new HashSet(0);
     private Set grnItems = new HashSet(0);
     private Set stocks = new HashSet(0);

    public Products() {
    }

	
    public Products(Discount discount, QtyType qtyType) {
        this.discount = discount;
        this.qtyType = qtyType;
    }
    public Products(Discount discount, QtyType qtyType, String proName, String proItrmCode, String description, String barcode, Integer status, Set CRetunItemses, Set SReturnItemses, Set qtyloosings, Set grnItems, Set stocks) {
       this.discount = discount;
       this.qtyType = qtyType;
       this.proName = proName;
       this.proItrmCode = proItrmCode;
       this.description = description;
       this.barcode = barcode;
       this.status = status;
       this.CRetunItemses = CRetunItemses;
       this.SReturnItemses = SReturnItemses;
       this.qtyloosings = qtyloosings;
       this.grnItems = grnItems;
       this.stocks = stocks;
    }
   
    public Integer getIdProducts() {
        return this.idProducts;
    }
    
    public void setIdProducts(Integer idProducts) {
        this.idProducts = idProducts;
    }
    public Discount getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Discount discount) {
        this.discount = discount;
    }
    public QtyType getQtyType() {
        return this.qtyType;
    }
    
    public void setQtyType(QtyType qtyType) {
        this.qtyType = qtyType;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public String getProItrmCode() {
        return this.proItrmCode;
    }
    
    public void setProItrmCode(String proItrmCode) {
        this.proItrmCode = proItrmCode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getCRetunItemses() {
        return this.CRetunItemses;
    }
    
    public void setCRetunItemses(Set CRetunItemses) {
        this.CRetunItemses = CRetunItemses;
    }
    public Set getSReturnItemses() {
        return this.SReturnItemses;
    }
    
    public void setSReturnItemses(Set SReturnItemses) {
        this.SReturnItemses = SReturnItemses;
    }
    public Set getQtyloosings() {
        return this.qtyloosings;
    }
    
    public void setQtyloosings(Set qtyloosings) {
        this.qtyloosings = qtyloosings;
    }
    public Set getGrnItems() {
        return this.grnItems;
    }
    
    public void setGrnItems(Set grnItems) {
        this.grnItems = grnItems;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }




}


