package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1



/**
 * Qtyloosing generated by hbm2java
 */
public class Qtyloosing  implements java.io.Serializable {


     private Integer idqtyLoosing;
     private Products products;
     private Stock stock;
     private Double qty;
     private String dateTime;

    public Qtyloosing() {
    }

	
    public Qtyloosing(Products products, Stock stock) {
        this.products = products;
        this.stock = stock;
    }
    public Qtyloosing(Products products, Stock stock, Double qty, String dateTime) {
       this.products = products;
       this.stock = stock;
       this.qty = qty;
       this.dateTime = dateTime;
    }
   
    public Integer getIdqtyLoosing() {
        return this.idqtyLoosing;
    }
    
    public void setIdqtyLoosing(Integer idqtyLoosing) {
        this.idqtyLoosing = idqtyLoosing;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }




}


