package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * QtyType generated by hbm2java
 */
public class QtyType  implements java.io.Serializable {


     private Integer idQtyType;
     private String typeName;
     private Integer status;
     private Set stocks = new HashSet(0);
     private Set productses = new HashSet(0);

    public QtyType() {
    }

    public QtyType(String typeName, Integer status, Set stocks, Set productses) {
       this.typeName = typeName;
       this.status = status;
       this.stocks = stocks;
       this.productses = productses;
    }
   
    public Integer getIdQtyType() {
        return this.idQtyType;
    }
    
    public void setIdQtyType(Integer idQtyType) {
        this.idQtyType = idQtyType;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


