package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SReturns generated by hbm2java
 */
public class SReturns  implements java.io.Serializable {


     private Integer idSReturns;
     private Grn grn;
     private String dateTime;
     private Set SReturnItemses = new HashSet(0);

    public SReturns() {
    }

	
    public SReturns(Grn grn) {
        this.grn = grn;
    }
    public SReturns(Grn grn, String dateTime, Set SReturnItemses) {
       this.grn = grn;
       this.dateTime = dateTime;
       this.SReturnItemses = SReturnItemses;
    }
   
    public Integer getIdSReturns() {
        return this.idSReturns;
    }
    
    public void setIdSReturns(Integer idSReturns) {
        this.idSReturns = idSReturns;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }
    public Set getSReturnItemses() {
        return this.SReturnItemses;
    }
    
    public void setSReturnItemses(Set SReturnItemses) {
        this.SReturnItemses = SReturnItemses;
    }




}


