package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1



/**
 * SReturnItems generated by hbm2java
 */
public class SReturnItems  implements java.io.Serializable {


     private Integer idSReturnItems;
     private Products products;
     private SReturns SReturns;
     private Double qty;
     private String reson;

    public SReturnItems() {
    }

	
    public SReturnItems(Products products, SReturns SReturns) {
        this.products = products;
        this.SReturns = SReturns;
    }
    public SReturnItems(Products products, SReturns SReturns, Double qty, String reson) {
       this.products = products;
       this.SReturns = SReturns;
       this.qty = qty;
       this.reson = reson;
    }
   
    public Integer getIdSReturnItems() {
        return this.idSReturnItems;
    }
    
    public void setIdSReturnItems(Integer idSReturnItems) {
        this.idSReturnItems = idSReturnItems;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public SReturns getSReturns() {
        return this.SReturns;
    }
    
    public void setSReturns(SReturns SReturns) {
        this.SReturns = SReturns;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public String getReson() {
        return this.reson;
    }
    
    public void setReson(String reson) {
        this.reson = reson;
    }




}


