package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1



/**
 * Stockupdated generated by hbm2java
 */
public class Stockupdated  implements java.io.Serializable {


     private Integer idStockUpdated;
     private Stock stock;
     private String reason;
     private String datetime;

    public Stockupdated() {
    }

	
    public Stockupdated(Stock stock) {
        this.stock = stock;
    }
    public Stockupdated(Stock stock, String reason, String datetime) {
       this.stock = stock;
       this.reason = reason;
       this.datetime = datetime;
    }
   
    public Integer getIdStockUpdated() {
        return this.idStockUpdated;
    }
    
    public void setIdStockUpdated(Integer idStockUpdated) {
        this.idStockUpdated = idStockUpdated;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(String datetime) {
        this.datetime = datetime;
    }




}


