package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer idstock;
     private Products products;
     private QtyType qtyType;
     private Double buyingPrice;
     private Double sellingPrice;
     private Double qty;
     private String buyDate;
     private String exdate;
     private Integer status;
     private Double discount;
     private Integer canloosing;
     private Set invoiceItems = new HashSet(0);
     private Set qtyloosings = new HashSet(0);
     private Set stockupdateds = new HashSet(0);
     private Set grnItems = new HashSet(0);

    public Stock() {
    }

	
    public Stock(Products products, QtyType qtyType) {
        this.products = products;
        this.qtyType = qtyType;
    }
    public Stock(Products products, QtyType qtyType, Double buyingPrice, Double sellingPrice, Double qty, String buyDate, String exdate, Integer status, Double discount, Integer canloosing, Set invoiceItems, Set qtyloosings, Set stockupdateds, Set grnItems) {
       this.products = products;
       this.qtyType = qtyType;
       this.buyingPrice = buyingPrice;
       this.sellingPrice = sellingPrice;
       this.qty = qty;
       this.buyDate = buyDate;
       this.exdate = exdate;
       this.status = status;
       this.discount = discount;
       this.canloosing = canloosing;
       this.invoiceItems = invoiceItems;
       this.qtyloosings = qtyloosings;
       this.stockupdateds = stockupdateds;
       this.grnItems = grnItems;
    }
   
    public Integer getIdstock() {
        return this.idstock;
    }
    
    public void setIdstock(Integer idstock) {
        this.idstock = idstock;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public QtyType getQtyType() {
        return this.qtyType;
    }
    
    public void setQtyType(QtyType qtyType) {
        this.qtyType = qtyType;
    }
    public Double getBuyingPrice() {
        return this.buyingPrice;
    }
    
    public void setBuyingPrice(Double buyingPrice) {
        this.buyingPrice = buyingPrice;
    }
    public Double getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(Double sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public String getBuyDate() {
        return this.buyDate;
    }
    
    public void setBuyDate(String buyDate) {
        this.buyDate = buyDate;
    }
    public String getExdate() {
        return this.exdate;
    }
    
    public void setExdate(String exdate) {
        this.exdate = exdate;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Integer getCanloosing() {
        return this.canloosing;
    }
    
    public void setCanloosing(Integer canloosing) {
        this.canloosing = canloosing;
    }
    public Set getInvoiceItems() {
        return this.invoiceItems;
    }
    
    public void setInvoiceItems(Set invoiceItems) {
        this.invoiceItems = invoiceItems;
    }
    public Set getQtyloosings() {
        return this.qtyloosings;
    }
    
    public void setQtyloosings(Set qtyloosings) {
        this.qtyloosings = qtyloosings;
    }
    public Set getStockupdateds() {
        return this.stockupdateds;
    }
    
    public void setStockupdateds(Set stockupdateds) {
        this.stockupdateds = stockupdateds;
    }
    public Set getGrnItems() {
        return this.grnItems;
    }
    
    public void setGrnItems(Set grnItems) {
        this.grnItems = grnItems;
    }




}


