package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1



/**
 * Supplierduerecords generated by hbm2java
 */
public class Supplierduerecords  implements java.io.Serializable {


     private int idDueRecords;
     private SupplierDue supplierDue;
     private String amount;
     private String datetime;

    public Supplierduerecords() {
    }

	
    public Supplierduerecords(int idDueRecords, SupplierDue supplierDue) {
        this.idDueRecords = idDueRecords;
        this.supplierDue = supplierDue;
    }
    public Supplierduerecords(int idDueRecords, SupplierDue supplierDue, String amount, String datetime) {
       this.idDueRecords = idDueRecords;
       this.supplierDue = supplierDue;
       this.amount = amount;
       this.datetime = datetime;
    }
   
    public int getIdDueRecords() {
        return this.idDueRecords;
    }
    
    public void setIdDueRecords(int idDueRecords) {
        this.idDueRecords = idDueRecords;
    }
    public SupplierDue getSupplierDue() {
        return this.supplierDue;
    }
    
    public void setSupplierDue(SupplierDue supplierDue) {
        this.supplierDue = supplierDue;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(String datetime) {
        this.datetime = datetime;
    }




}


