package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SupplierDue generated by hbm2java
 */
public class SupplierDue  implements java.io.Serializable {


     private Integer idSupplierDue;
     private Grn grn;
     private Supplier supplier;
     private Double total;
     private Double dueamount;
     private Set supplierduerecordses = new HashSet(0);

    public SupplierDue() {
    }

	
    public SupplierDue(Grn grn, Supplier supplier) {
        this.grn = grn;
        this.supplier = supplier;
    }
    public SupplierDue(Grn grn, Supplier supplier, Double total, Double dueamount, Set supplierduerecordses) {
       this.grn = grn;
       this.supplier = supplier;
       this.total = total;
       this.dueamount = dueamount;
       this.supplierduerecordses = supplierduerecordses;
    }
   
    public Integer getIdSupplierDue() {
        return this.idSupplierDue;
    }
    
    public void setIdSupplierDue(Integer idSupplierDue) {
        this.idSupplierDue = idSupplierDue;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getDueamount() {
        return this.dueamount;
    }
    
    public void setDueamount(Double dueamount) {
        this.dueamount = dueamount;
    }
    public Set getSupplierduerecordses() {
        return this.supplierduerecordses;
    }
    
    public void setSupplierduerecordses(Set supplierduerecordses) {
        this.supplierduerecordses = supplierduerecordses;
    }




}


