package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer idSupplier;
     private String name;
     private String email;
     private String mobile;
     private String lanNo;
     private String company;
     private String address01;
     private String address02;
     private String address03;
     private Integer status;
     private Set supplierDues = new HashSet(0);
     private Set grns = new HashSet(0);

    public Supplier() {
    }

    public Supplier(String name, String email, String mobile, String lanNo, String company, String address01, String address02, String address03, Integer status, Set supplierDues, Set grns) {
       this.name = name;
       this.email = email;
       this.mobile = mobile;
       this.lanNo = lanNo;
       this.company = company;
       this.address01 = address01;
       this.address02 = address02;
       this.address03 = address03;
       this.status = status;
       this.supplierDues = supplierDues;
       this.grns = grns;
    }
   
    public Integer getIdSupplier() {
        return this.idSupplier;
    }
    
    public void setIdSupplier(Integer idSupplier) {
        this.idSupplier = idSupplier;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getLanNo() {
        return this.lanNo;
    }
    
    public void setLanNo(String lanNo) {
        this.lanNo = lanNo;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getAddress01() {
        return this.address01;
    }
    
    public void setAddress01(String address01) {
        this.address01 = address01;
    }
    public String getAddress02() {
        return this.address02;
    }
    
    public void setAddress02(String address02) {
        this.address02 = address02;
    }
    public String getAddress03() {
        return this.address03;
    }
    
    public void setAddress03(String address03) {
        this.address03 = address03;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getSupplierDues() {
        return this.supplierDues;
    }
    
    public void setSupplierDues(Set supplierDues) {
        this.supplierDues = supplierDues;
    }
    public Set getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set grns) {
        this.grns = grns;
    }




}


