package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserWindow generated by hbm2java
 */
public class UserWindow  implements java.io.Serializable {


     private Integer idUserPage;
     private String pageName;
     private String url;
     private Integer status;
     private Set usertypeHasWindows = new HashSet(0);

    public UserWindow() {
    }

    public UserWindow(String pageName, String url, Integer status, Set usertypeHasWindows) {
       this.pageName = pageName;
       this.url = url;
       this.status = status;
       this.usertypeHasWindows = usertypeHasWindows;
    }
   
    public Integer getIdUserPage() {
        return this.idUserPage;
    }
    
    public void setIdUserPage(Integer idUserPage) {
        this.idUserPage = idUserPage;
    }
    public String getPageName() {
        return this.pageName;
    }
    
    public void setPageName(String pageName) {
        this.pageName = pageName;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getUsertypeHasWindows() {
        return this.usertypeHasWindows;
    }
    
    public void setUsertypeHasWindows(Set usertypeHasWindows) {
        this.usertypeHasWindows = usertypeHasWindows;
    }




}


