package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer idUserType;
     private String typeName;
     private Integer status;
     private Set usertypeHasWindows = new HashSet(0);
     private Set userLogins = new HashSet(0);

    public UserType() {
    }

    public UserType(String typeName, Integer status, Set usertypeHasWindows, Set userLogins) {
       this.typeName = typeName;
       this.status = status;
       this.usertypeHasWindows = usertypeHasWindows;
       this.userLogins = userLogins;
    }
   
    public Integer getIdUserType() {
        return this.idUserType;
    }
    
    public void setIdUserType(Integer idUserType) {
        this.idUserType = idUserType;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getUsertypeHasWindows() {
        return this.usertypeHasWindows;
    }
    
    public void setUsertypeHasWindows(Set usertypeHasWindows) {
        this.usertypeHasWindows = usertypeHasWindows;
    }
    public Set getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set userLogins) {
        this.userLogins = userLogins;
    }




}


