package BPos.DB;
// Generated Aug 23, 2016 10:19:13 AM by Hibernate Tools 4.3.1



/**
 * UsertypeHasWindow generated by hbm2java
 */
public class UsertypeHasWindow  implements java.io.Serializable {


     private Integer userTypeHasPage;
     private UserType userType;
     private UserWindow userWindow;

    public UsertypeHasWindow() {
    }

    public UsertypeHasWindow(UserType userType, UserWindow userWindow) {
       this.userType = userType;
       this.userWindow = userWindow;
    }
   
    public Integer getUserTypeHasPage() {
        return this.userTypeHasPage;
    }
    
    public void setUserTypeHasPage(Integer userTypeHasPage) {
        this.userTypeHasPage = userTypeHasPage;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public UserWindow getUserWindow() {
        return this.userWindow;
    }
    
    public void setUserWindow(UserWindow userWindow) {
        this.userWindow = userWindow;
    }




}


