/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package BPos.View;

import BPos.DB.Supplier;
import java.awt.Color;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author BHANU
 */
public class Add_Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Add_Supplier
     */
    private static String SelectedValue = "";

    public Add_Supplier() {
        initComponents();
        BTN_DELETE.setEnabled(false);
        BTN_UPDATE.setEnabled(false);
        loadSupplier();
        String s[] = {"name", "mobile", "lanNo", "email", "company"};
        for (String s1 : s) {
            COMBO_SEARCH.addItem(s1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SupplirPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        COMBO_SEARCH = new javax.swing.JComboBox();
        TEXT_SEARCH = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TEXT_NAME = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TEXT_MOB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TEXT_LAN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TEXT_ADD1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TEXT_ADD2 = new javax.swing.JTextField();
        TEXT_ADD3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BTN_SAVE = new javax.swing.JButton();
        BTN_UPDATE = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TEXT_EMAIL = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TEXT_COMPANY = new javax.swing.JTextField();
        BTN_SAVE1 = new javax.swing.JButton();
        BTN_DELETE = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        LAB_COUNT = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Supplier");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        SupplirPanel.setBackground(new java.awt.Color(255, 255, 255));
        SupplirPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel1.setText("Search By :");

        TEXT_SEARCH.setForeground(new java.awt.Color(204, 204, 204));
        TEXT_SEARCH.setText(" Search Supplier");
        TEXT_SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXT_SEARCHActionPerformed(evt);
            }
        });
        TEXT_SEARCH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TEXT_SEARCHFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TEXT_SEARCHFocusLost(evt);
            }
        });
        TEXT_SEARCH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_SEARCHKeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Basic Details"));

        jLabel4.setText("Name :");

        TEXT_NAME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TEXT_NAMEFocusGained(evt);
            }
        });

        jLabel5.setText("Mobile No :");

        TEXT_MOB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TEXT_MOBFocusGained(evt);
            }
        });
        TEXT_MOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_MOBKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TEXT_MOBKeyTyped(evt);
            }
        });

        jLabel6.setText("Lan No    :");

        TEXT_LAN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_LANKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TEXT_LANKeyTyped(evt);
            }
        });

        jLabel7.setText("Address 1 :");

        TEXT_ADD1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TEXT_ADD1FocusGained(evt);
            }
        });

        jLabel8.setText("Address 2 :");

        jLabel9.setText("Address 3 :");

        BTN_SAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/btn/data-recovery-64.png"))); // NOI18N
        BTN_SAVE.setText("Save");
        BTN_SAVE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        BTN_SAVE.setContentAreaFilled(false);
        BTN_SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SAVEActionPerformed(evt);
            }
        });

        BTN_UPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/btn/updateL.png"))); // NOI18N
        BTN_UPDATE.setText("Update");
        BTN_UPDATE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        BTN_UPDATE.setContentAreaFilled(false);
        BTN_UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_UPDATEActionPerformed(evt);
            }
        });

        jLabel10.setText("Email :");

        jLabel11.setText("Company :");

        TEXT_COMPANY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TEXT_COMPANYFocusGained(evt);
            }
        });

        BTN_SAVE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/btn/Reset S.png"))); // NOI18N
        BTN_SAVE1.setText("Clear");
        BTN_SAVE1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        BTN_SAVE1.setContentAreaFilled(false);
        BTN_SAVE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SAVE1ActionPerformed(evt);
            }
        });

        BTN_DELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/btn/Delete DB L.png"))); // NOI18N
        BTN_DELETE.setText("Delete");
        BTN_DELETE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        BTN_DELETE.setContentAreaFilled(false);
        BTN_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DELETEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(TEXT_NAME, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TEXT_ADD1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TEXT_EMAIL, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))))
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(TEXT_MOB, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TEXT_ADD2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TEXT_COMPANY, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(TEXT_LAN, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(TEXT_ADD3, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_SAVE1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTN_SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTN_UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTN_DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TEXT_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TEXT_MOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TEXT_LAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TEXT_ADD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(TEXT_ADD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TEXT_ADD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TEXT_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(TEXT_COMPANY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN_SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_SAVE1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jLabel2.setText("Supplier Count :");

        LAB_COUNT.setText("000");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cus ID", "Name", "Mobile", "Lan No", "Address 01", "Address 02", "Address 03", "Email ", "Company"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout SupplirPanelLayout = new javax.swing.GroupLayout(SupplirPanel);
        SupplirPanel.setLayout(SupplirPanelLayout);
        SupplirPanelLayout.setHorizontalGroup(
            SupplirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(SupplirPanelLayout.createSequentialGroup()
                .addGroup(SupplirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SupplirPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SupplirPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(COMBO_SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, Short.MAX_VALUE)
                        .addComponent(TEXT_SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SupplirPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(SupplirPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(LAB_COUNT, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SupplirPanelLayout.setVerticalGroup(
            SupplirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SupplirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(COMBO_SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SupplirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LAB_COUNT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SupplirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SupplirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1016, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TEXT_SEARCHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TEXT_SEARCHFocusLost

    }//GEN-LAST:event_TEXT_SEARCHFocusLost

    private void TEXT_SEARCHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TEXT_SEARCHFocusGained

    }//GEN-LAST:event_TEXT_SEARCHFocusGained

    private void TEXT_SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXT_SEARCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXT_SEARCHActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void BTN_SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SAVEActionPerformed
        try {
            if (!TEXT_NAME.getText().equals("")
                    & !TEXT_MOB.getText().equals("")
                    & !TEXT_LAN.getText().equals("")
                    & !TEXT_ADD1.getText().equals("")
                    & !TEXT_ADD2.getText().equals("")
                    & !TEXT_ADD3.getText().equals("")
                    & !TEXT_EMAIL.getText().equals("")
                    & !TEXT_COMPANY.getText().equals("")) {
                if (2 < TEXT_NAME.getText().length()) {
                    if (Com.execute.validation.Validation.isNumber(TEXT_MOB.getText())) {
                        if (Com.execute.validation.Validation.isNumber(TEXT_LAN.getText())) {
                            if (2 < TEXT_ADD1.getText().length()) {
                                if (2 < TEXT_ADD2.getText().length()) {
                                    if (2 < TEXT_ADD3.getText().length()) {
                                        if (Com.execute.validation.Validation.isvalidEmail(TEXT_EMAIL.getText())) {
                                            if (2 < TEXT_COMPANY.getText().length()) {
                                                BPos.DB.Supplier sup = new Supplier();
                                                sup.setName(TEXT_NAME.getText());
                                                sup.setMobile(TEXT_MOB.getText());
                                                sup.setLanNo(TEXT_LAN.getText());
                                                sup.setAddress01(TEXT_ADD1.getText());
                                                sup.setAddress02(TEXT_ADD2.getText());
                                                sup.setAddress03(TEXT_ADD3.getText());
                                                sup.setEmail(TEXT_EMAIL.getText());
                                                sup.setCompany(TEXT_COMPANY.getText());
                                                String s = BPos.Model.Supplier.saveSupplier(sup);
                                                if (s.equals("done")) {
                                                    JOptionPane.showMessageDialog(rootPane, "Save Done!");
                                                    loadSupplier();
                                                    clearTEXT();
                                                } else {
                                                    JOptionPane.showMessageDialog(rootPane, "Save Error!");
                                                }
                                            } else {
                                                JOptionPane.showMessageDialog(rootPane, "please enter valid company name Address!");
                                            }
                                        } else {
                                            JOptionPane.showMessageDialog(rootPane, "please enter valid Email Address!");
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(rootPane, "please enter valid address3. 2 + length");
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(rootPane, "please enter valid address2. 2 + length");
                                }
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "please enter valid address1. 2 + length");
                            }
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "please enter valid lan number. 2 + length");
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "please enter valid mobile number. 2 + length");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "please enter valid name. 2 + length");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Fields is empty");
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_BTN_SAVEActionPerformed

    private void TEXT_MOBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_MOBKeyTyped
       char c = evt.getKeyChar();

        if (!(c >= '0' && c <= '9')) {

            evt.consume();

        }
    }//GEN-LAST:event_TEXT_MOBKeyTyped

    private void TEXT_LANKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_LANKeyTyped
               char c = evt.getKeyChar();

        if (!(c >= '0' && c <= '9')) {

            evt.consume();

        }
    }//GEN-LAST:event_TEXT_LANKeyTyped

    private void TEXT_SEARCHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_SEARCHKeyReleased
        try {
            if (TEXT_SEARCH.getText().equals("")) {
                loadSupplier();
            } else {
                Vector v1 = new Vector();
                DefaultTableModel dt = (DefaultTableModel) jTable2.getModel();
                Session ses = BPos.Connection.NewHibernateUtil.getSessionFactory().openSession();
                Criteria cr = ses.createCriteria(BPos.DB.Supplier.class);
                cr.add(Restrictions.eq(COMBO_SEARCH.getSelectedItem().toString(), TEXT_SEARCH.getText()));
                List<BPos.DB.Supplier> l = cr.list();
                dt.setRowCount(0);
                for (Supplier l1 : l) {
                    Vector v = new Vector();
                    v.add(l1.getIdSupplier());
                    v.add(l1.getName());
                    v.add(l1.getMobile());
                    v.add(l1.getLanNo());
                    v.add(l1.getAddress01());
                    v.add(l1.getAddress02());
                    v.add(l1.getAddress03());
                    v.add(l1.getEmail());
                    v.add(l1.getCompany());
                    v1.add(v);
                }
                for (int i = 0; i < v1.size(); i++) {
                    Vector elementAt = (Vector) v1.elementAt(i);
                    dt.addRow(elementAt);
                }
                ses.close();
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_TEXT_SEARCHKeyReleased

    private void BTN_UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_UPDATEActionPerformed
        try {
            if (!TEXT_NAME.getText().equals("")
                    & !TEXT_MOB.getText().equals("")
                    & !TEXT_LAN.getText().equals("")
                    & !TEXT_ADD1.getText().equals("")
                    & !TEXT_ADD2.getText().equals("")
                    & !TEXT_ADD3.getText().equals("")
                    & !TEXT_EMAIL.getText().equals("")
                    & !TEXT_COMPANY.getText().equals("")) {
                BPos.DB.Supplier sup = new Supplier();
                sup.setIdSupplier(Integer.parseInt(SelectedValue));
                sup.setName(TEXT_NAME.getText());
                sup.setMobile(TEXT_MOB.getText());
                sup.setLanNo(TEXT_LAN.getText());
                sup.setAddress01(TEXT_ADD1.getText());
                sup.setAddress02(TEXT_ADD2.getText());
                sup.setAddress03(TEXT_ADD3.getText());
                sup.setEmail(TEXT_EMAIL.getText());
                sup.setCompany(TEXT_COMPANY.getText());
                String s = BPos.Model.Supplier.updateSupplier(sup);
                if (s.equals("done")) {
                    JOptionPane.showMessageDialog(rootPane, "Update Done!");
                    loadSupplier();
                    clearTEXT();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Update Error!");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Fields is empty");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BTN_UPDATEActionPerformed

    private void TEXT_NAMEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TEXT_NAMEFocusGained

    }//GEN-LAST:event_TEXT_NAMEFocusGained

    private void TEXT_MOBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TEXT_MOBFocusGained

    }//GEN-LAST:event_TEXT_MOBFocusGained

    private void TEXT_ADD1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TEXT_ADD1FocusGained

    }//GEN-LAST:event_TEXT_ADD1FocusGained

    private void TEXT_COMPANYFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TEXT_COMPANYFocusGained

    }//GEN-LAST:event_TEXT_COMPANYFocusGained

    private void BTN_SAVE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SAVE1ActionPerformed
        clearTEXT();
    }//GEN-LAST:event_BTN_SAVE1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        try {
            JTable target = (JTable) evt.getSource();
            BTN_SAVE.setEnabled(false);
            int selectedRow = target.getSelectedRow();
            int selectedColumn = target.getSelectedColumn();

            Object value = target.getValueAt(selectedRow, 0);
            SelectedValue = value.toString();
            Session ses = BPos.Connection.NewHibernateUtil.getSessionFactory().openSession();
            Criteria cr = ses.createCriteria(BPos.DB.Supplier.class);
            cr.add(Restrictions.eq("idSupplier", value));
            List<BPos.DB.Supplier> cs = cr.list();
            for (Supplier c : cs) {
                TEXT_NAME.setText(c.getName());
                TEXT_MOB.setText(c.getMobile());
                TEXT_LAN.setText(c.getLanNo());
                TEXT_ADD1.setText(c.getAddress01());
                TEXT_ADD2.setText(c.getAddress02());
                TEXT_ADD3.setText(c.getAddress03());
                TEXT_EMAIL.setText(c.getEmail());
                TEXT_COMPANY.setText(c.getCompany());
            }
            BTN_DELETE.setEnabled(true);
            BTN_UPDATE.setEnabled(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jTable2MouseClicked

    private void BTN_DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DELETEActionPerformed

        try {
            if (!SelectedValue.equals("")) {
                new BPos.Model.Supplier().DeleteSupplier(Integer.parseInt(SelectedValue));
                loadSupplier();
                clearTEXT();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BTN_DELETEActionPerformed

    private void TEXT_MOBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_MOBKeyReleased
        if (0 < TEXT_MOB.getText().length() & 10 == TEXT_MOB.getText().length()) {
            TEXT_MOB.setForeground(Color.BLACK);
        } else {
            TEXT_MOB.setForeground(Color.red);
        }
    }//GEN-LAST:event_TEXT_MOBKeyReleased

    private void TEXT_LANKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_LANKeyReleased
        // TODO add your handling code here:
        if (0 < TEXT_LAN.getText().length() & 10 == TEXT_LAN.getText().length()) {
            TEXT_LAN.setForeground(Color.black);
        }else{
            TEXT_LAN.setForeground(Color.red);
        }
    }//GEN-LAST:event_TEXT_LANKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Supplier().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_DELETE;
    private javax.swing.JButton BTN_SAVE;
    private javax.swing.JButton BTN_SAVE1;
    private javax.swing.JButton BTN_UPDATE;
    private javax.swing.JComboBox COMBO_SEARCH;
    private javax.swing.JLabel LAB_COUNT;
    public javax.swing.JPanel SupplirPanel;
    private javax.swing.JTextField TEXT_ADD1;
    private javax.swing.JTextField TEXT_ADD2;
    private javax.swing.JTextField TEXT_ADD3;
    private javax.swing.JTextField TEXT_COMPANY;
    private javax.swing.JTextField TEXT_EMAIL;
    private javax.swing.JTextField TEXT_LAN;
    private javax.swing.JTextField TEXT_MOB;
    private javax.swing.JTextField TEXT_NAME;
    private javax.swing.JTextField TEXT_SEARCH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    public void loadSupplier() {
        repaint();
        Vector v1 = new Vector();
        DefaultTableModel dt = (DefaultTableModel) jTable2.getModel();
        Session ses = BPos.Connection.NewHibernateUtil.getSessionFactory().openSession();
        Criteria cr = ses.createCriteria(BPos.DB.Supplier.class);
        List<BPos.DB.Supplier> l = cr.list();
        dt.setRowCount(0);
        for (Supplier l1 : l) {
            Vector v = new Vector();
            v.add(l1.getIdSupplier());
            v.add(l1.getName());
            v.add(l1.getMobile());
            v.add(l1.getLanNo());
            v.add(l1.getAddress01());
            v.add(l1.getAddress02());
            v.add(l1.getAddress03());
            v.add(l1.getEmail());
            v.add(l1.getCompany());
            v1.add(v);
        }
        for (int i = 0; i < v1.size(); i++) {
            Vector elementAt = (Vector) v1.elementAt(i);
            dt.addRow(elementAt);
        }
        ses.close();
    }

    public void clearTEXT() {
        TEXT_ADD1.setText("");
        TEXT_ADD2.setText("");
        TEXT_ADD3.setText("");
        TEXT_LAN.setText("");
        TEXT_MOB.setText("");
        TEXT_NAME.setText("");
        TEXT_EMAIL.setText("");
        TEXT_COMPANY.setText("");
        BTN_DELETE.setEnabled(false);
        BTN_UPDATE.setEnabled(false);
        BTN_SAVE.setEnabled(true);
    }

}
