/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package BPos.View;

import BPos.DB.GrnItem;
import BPos.DB.PaymentType;
import BPos.DB.Stock;
import BPos.DB.SupplierDue;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;
import org.hibernate.jdbc.Work;

/**
 *
 * @author Bhagya
 */
public class Grn extends javax.swing.JFrame {

    int IDSup;
    public int ID_Product;

    public Grn() {
        initComponents();
        onload();
    }
    Grn grn;
    Vector v = new Vector();

    public Grn(Grn g, BPos.Model.itemsList il) {
        Vector v1 = new Vector();
        v1.add(il.getProductID());
        v1.add(il.getName());
        v1.add(il.getDescription());
        v1.add(il.getQty());
        v1.add(il.getPrice());
        v1.add(il.getSellingPrice());
        v1.add(il.getSubAmount());
        if (il.getExDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String strdtver1 = (String) sdf.format(il.getExDate());
            v1.add(strdtver1);
        } else {
            v1.add(null);
        }
        v1.add(il.getDiscount() + "%");
        v1.add(il.getTypes().getTypeName());
        v1.add(il.getCanLoosing());
        v = v1;
        grn = g;
        load();
        Total();
    }

    public void onload() {
        try {
            Session ses = BPos.Connection.NewHibernateUtil.getSessionFactory().openSession();
            Criteria cr = ses.createCriteria(BPos.DB.PaymentType.class);
            List<BPos.DB.PaymentType> pt = cr.list();
            for (PaymentType pt1 : pt) {
                COMBO_PAYMENT_TYPE.addItem(pt1.getTypename() + "_" + pt1.getIdPaymentType());
            }
            ses.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Total() {
        try {

            DefaultTableModel dmt = (DefaultTableModel) grn.jTable1.getModel();

            double id = 0;
            for (int i = 0; i < grn.jTable1.getRowCount(); i++) {
                id += Double.parseDouble(dmt.getValueAt(i, 6).toString());
                grn.TEXT_SUBTOTAL.setText(id + "");
                grn.TEXT_GRAND_TOTAL.setText(id + "");
                grn.TEXT_PAID.setText(id + "");
                grn.rowcount.setText(i + "");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Total_Again() {
        try {

            DefaultTableModel dmt = (DefaultTableModel) jTable1.getModel();

            double id = 0;
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                id += Double.parseDouble(dmt.getValueAt(i, 6).toString());
                TEXT_SUBTOTAL.setText(id + "");
                TEXT_GRAND_TOTAL.setText(id + "");
                TEXT_PAID.setText(id + "");
                rowcount.setText(i + "");
            }
            if (dmt.getRowCount() == 0) {
                Clear();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void load() {
        try {
            DefaultTableModel dt = (DefaultTableModel) grn.jTable1.getModel();
            dt.addRow(v);
        } catch (Exception e) {
        }
    }

    public Grn(Grn GRN, int id) {
        initComponents();
        loadSupplier(id, GRN);
    }

    public void loadSupplier(int id, Grn g) {
        Session ses = BPos.Connection.NewHibernateUtil.getSessionFactory().openSession();
        BPos.DB.Supplier sup = (BPos.DB.Supplier) ses.load(BPos.DB.Supplier.class, id);
        g.sup_name.setText(sup.getName());
        g.company.setText(sup.getCompany());
        g.idsupplier.setText(sup.getIdSupplier() + "");
        ses.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grnPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TEXT_SUBTOTAL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        COMBO_PAYMENT_TYPE = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TEXT_PAID = new javax.swing.JTextField();
        TEXT_BALANCE = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TEXT_DISCOUNT = new javax.swing.JTextField();
        TEXT_GRAND_TOTAL = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DueAmount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rowcount = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BTN_SAVE = new javax.swing.JButton();
        BTN_UPDATE = new javax.swing.JButton();
        BTN_DELETE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sup_name = new javax.swing.JLabel();
        company = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        idsupplier = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        grnPanel.setBackground(new java.awt.Color(255, 255, 255));
        grnPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Description", "Quantity", "Buying Price", "Selling Price", "Amount", "Expire Date", "Discount", "Qty_Type", "CanLoosing"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Sub Total : ");

        TEXT_SUBTOTAL.setEditable(false);
        TEXT_SUBTOTAL.setText("0.00");

        jLabel5.setText("Discount :");

        jLabel7.setText("Payment Type :");

        jLabel8.setText("Paid :");

        jLabel10.setText("Balance :");

        TEXT_PAID.setText("0.00");
        TEXT_PAID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_PAIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TEXT_PAIDKeyTyped(evt);
            }
        });

        TEXT_BALANCE.setEditable(false);
        TEXT_BALANCE.setText("0.00");
        TEXT_BALANCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXT_BALANCEActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("LKR");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("LKR");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("LKR");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("%");

        TEXT_DISCOUNT.setText("0");
        TEXT_DISCOUNT.setToolTipText("");
        TEXT_DISCOUNT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TEXT_DISCOUNTKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TEXT_DISCOUNTKeyTyped(evt);
            }
        });

        TEXT_GRAND_TOTAL.setEditable(false);
        TEXT_GRAND_TOTAL.setText("0.00");
        TEXT_GRAND_TOTAL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TEXT_GRAND_TOTALKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("LKR");

        jLabel9.setText("Grand Total :");

        DueAmount.setEditable(false);
        DueAmount.setText("0.00");
        DueAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DueAmountActionPerformed(evt);
            }
        });

        jLabel13.setText("Due Amount :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("LKR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TEXT_SUBTOTAL, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TEXT_DISCOUNT)
                            .addComponent(TEXT_GRAND_TOTAL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(COMBO_PAYMENT_TYPE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TEXT_PAID, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DueAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TEXT_BALANCE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXT_SUBTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(TEXT_DISCOUNT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXT_GRAND_TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXT_PAID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(COMBO_PAYMENT_TYPE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXT_BALANCE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DueAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel20))
                .addGap(40, 40, 40))
        );

        jLabel17.setText("Supplier :");

        jTextField8.setEditable(false);
        jTextField8.setText("        Click Here");
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)));
        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField8MousePressed(evt);
            }
        });
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setEditable(false);
        jTextField9.setText("      Add Products");
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)));
        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField9MousePressed(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel2.setText("Grn Item Count :");

        rowcount.setText("000");

        BTN_SAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/btn/data-recovery-64.png"))); // NOI18N
        BTN_SAVE.setText("Save");
        BTN_SAVE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        BTN_SAVE.setContentAreaFilled(false);
        BTN_SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SAVEActionPerformed(evt);
            }
        });

        BTN_UPDATE.setText("Remove Item");
        BTN_UPDATE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        BTN_UPDATE.setContentAreaFilled(false);
        BTN_UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_UPDATEActionPerformed(evt);
            }
        });

        BTN_DELETE.setText("Clear");
        BTN_DELETE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        BTN_DELETE.setContentAreaFilled(false);
        BTN_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DELETEActionPerformed(evt);
            }
        });

        jLabel1.setText("Supplier Name : ");

        jLabel18.setText("Company         :");

        javax.swing.GroupLayout grnPanelLayout = new javax.swing.GroupLayout(grnPanel);
        grnPanel.setLayout(grnPanelLayout);
        grnPanelLayout.setHorizontalGroup(
            grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grnPanelLayout.createSequentialGroup()
                .addGroup(grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grnPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(grnPanelLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(2, 2, 2)
                                .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 439, Short.MAX_VALUE)
                                .addComponent(jLabel17))
                            .addGroup(grnPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2)
                                .addComponent(sup_name, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grnPanelLayout.createSequentialGroup()
                        .addGroup(grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(grnPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(rowcount, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idsupplier)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grnPanelLayout.createSequentialGroup()
                                .addComponent(BTN_SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTN_UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTN_DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
        );
        grnPanelLayout.setVerticalGroup(
            grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grnPanelLayout.createSequentialGroup()
                .addGroup(grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(grnPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(grnPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(sup_name, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rowcount)
                    .addComponent(BTN_SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idsupplier))
                .addContainerGap())
            .addGroup(grnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(grnPanelLayout.createSequentialGroup()
                    .addGap(498, 498, 498)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1016, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int opt = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to close the Window ?", "Warning", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MousePressed

    }//GEN-LAST:event_jTextField9MousePressed

    private void jTextField8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MousePressed

    }//GEN-LAST:event_jTextField8MousePressed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed

    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
        Add_Supplier_GRN g = new Add_Supplier_GRN(this);
        g.setVisible(true);
    }//GEN-LAST:event_jTextField8MouseClicked

    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
        Add_Grn_Items ag = new Add_Grn_Items(this);
        ag.setVisible(true);
    }//GEN-LAST:event_jTextField9MouseClicked

    private void TEXT_BALANCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXT_BALANCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXT_BALANCEActionPerformed

    private void TEXT_PAIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_PAIDKeyTyped
        char c = evt.getKeyChar();
        if (!(c >= '0' && c <= '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_TEXT_PAIDKeyTyped

    private void TEXT_DISCOUNTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_DISCOUNTKeyTyped
        char c = evt.getKeyChar();
        if (!(c >= '0' && c <= '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_TEXT_DISCOUNTKeyTyped

    private void TEXT_GRAND_TOTALKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_GRAND_TOTALKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXT_GRAND_TOTALKeyTyped

    private void TEXT_DISCOUNTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_DISCOUNTKeyReleased
        if (!TEXT_SUBTOTAL.getText().equals("") & !TEXT_DISCOUNT.getText().equals("")) {
            double sub = Double.parseDouble(TEXT_SUBTOTAL.getText());
            int di = Integer.parseInt(TEXT_DISCOUNT.getText());
            double s = sub * di / 100;
            sub = sub - s;
            TEXT_GRAND_TOTAL.setText(sub + "");
        }
    }//GEN-LAST:event_TEXT_DISCOUNTKeyReleased

    private void TEXT_PAIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEXT_PAIDKeyReleased
        try {
            if (!TEXT_PAID.getText().equals("")) {
                TEXT_PAID.setBackground(Color.white);
                double d = Double.parseDouble(TEXT_GRAND_TOTAL.getText());
                double f = Double.parseDouble(TEXT_PAID.getText());
                if (d <= f) {
                    TEXT_BALANCE.setForeground(Color.black);
                    TEXT_BALANCE.setText(f - d + "");
                    DueAmount.setText("0.0");
                } else {
                    TEXT_BALANCE.setForeground(Color.red);
                    TEXT_BALANCE.setText("0.0");
                    DueAmount.setText(d - f + "");
                }
            } else {
                DueAmount.setText("0.0");
                TEXT_PAID.setBackground(Color.red);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_TEXT_PAIDKeyReleased

    private void BTN_SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SAVEActionPerformed
        try {
            if (!sup_name.getText().equals("")) {
                if (!TEXT_GRAND_TOTAL.getText().equals("") & !TEXT_DISCOUNT.getText().equals("") & !TEXT_SUBTOTAL.getText().equals("") & !TEXT_PAID.getText().equals("") & !TEXT_BALANCE.getText().equals("") & COMBO_PAYMENT_TYPE.getSelectedIndex() != -1) {
                    final Session ses = BPos.Connection.NewHibernateUtil.getSessionFactory().openSession();
                    Transaction tr = ses.beginTransaction();
                    final BPos.DB.Grn G_R_N = new BPos.DB.Grn();
                    BPos.DB.Supplier sup = (BPos.DB.Supplier) ses.load(BPos.DB.Supplier.class, Integer.parseInt(idsupplier.getText()));
                    G_R_N.setSupplier(sup);
                    SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                    String date1 = sdf1.format(new Date());
                    G_R_N.setDateTime(date1);
                    String ar[] = COMBO_PAYMENT_TYPE.getSelectedItem().toString().split("_");
                    final PaymentType pt = (PaymentType) ses.load(BPos.DB.PaymentType.class, Integer.parseInt(ar[1]));
                    G_R_N.setPaymentType(pt);
                    G_R_N.setTotalAmount(Double.parseDouble(TEXT_GRAND_TOTAL.getText()));
                    ses.save(G_R_N);

                    DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();

                    String itemcode = null;
                    double buPrice = 0;
                    double sellingPrice = 0;
                    double amount = 0;
                    double qty = 0;

                    int discount = 0;
                    String CanLoosing = "";
                    BPos.DB.QtyType QtyType = null;

                    for (int i = 0; i < jTable1.getRowCount(); i++) {
                        GrnItem gi = new GrnItem();
                        gi.setGrn(G_R_N);
                        itemcode = (String) dt.getValueAt(i, 0);
                        BPos.DB.Products pro = (BPos.DB.Products) ses.load(BPos.DB.Products.class, Integer.parseInt(itemcode));
                        gi.setProducts(pro);
                        qty = (double) dt.getValueAt(i, 3);
                        gi.setQty(qty);
                        buPrice = (double) dt.getValueAt(i, 4);
                        gi.setUnitPrice(buPrice);
                        sellingPrice = (double) dt.getValueAt(i, 5);
                        gi.setSellingPrice(sellingPrice);
                        amount = (double) dt.getValueAt(i, 6);
                        gi.setSubTotal(amount);

                        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                        String date = sdf.format(new Date());

                        String dis = (String) dt.getValueAt(i, 8);
                        String ar1[] = dis.split("%");
                        double Disco = Double.parseDouble(ar1[0]);
                        
                        BPos.DB.Stock sck = new Stock();
                        sck.setProducts(pro);
                        sck.setStatus(1);
                        sck.setBuyingPrice(buPrice);
                        sck.setSellingPrice(sellingPrice);
                        sck.setBuyDate(date);
                        sck.setExdate(dt.getValueAt(i, 7).toString());
                        sck.setQty(qty);
                        
                        String cl = (String) dt.getValueAt(i, 10);
                        String QT = (String) dt.getValueAt(i, 9);
                        
                        Session ses1 = BPos.Connection.NewHibernateUtil.getSessionFactory().openSession();
                        Criteria cr1 = ses1.createCriteria(BPos.DB.QtyType.class);
                        cr1.add(Restrictions.eq("typeName", QT));
                        
                        BPos.DB.QtyType qtypT = (BPos.DB.QtyType) cr1.uniqueResult();
                        
                        int CanLoce = 0;
                        if(cl.equals("Yes")){
                            CanLoce = 1;
                        }
                        sck.setCanloosing(CanLoce);
                        sck.setQtyType(qtypT);
                        ses1.close();
                        sck.setDiscount(Disco);

                        ses.save(sck);

                        gi.setStock(sck);
                        ses.save(gi);

                        BPos.DB.SupplierDue sdue = new SupplierDue();
                        sdue.setDueamount(Double.parseDouble(DueAmount.getText()));
                        sdue.setGrn(G_R_N);
                        sdue.setSupplier(sup);
                        sdue.setTotal(Double.parseDouble(TEXT_GRAND_TOTAL.getText()));
                        ses.save(sdue);

                    }
                    tr.commit();
                    ses.flush();
                    int opt = JOptionPane.showConfirmDialog(rootPane, "Are you want print grn?", "Warning", JOptionPane.YES_NO_OPTION);
                    if (opt == 0) {
                        ses.doWork(new Work() {
                            @Override
                            public void execute(Connection cnctn) throws SQLException {
                                try {
                                    Map<String, Object> params = new HashMap<String, Object>();
                                    
                                    params.put("grnId", G_R_N.getGrnId());
                                    params.put("totamount", TEXT_SUBTOTAL.getText());
                                    params.put("discount", TEXT_DISCOUNT.getText() + "%");
                                    params.put("grandtot", TEXT_GRAND_TOTAL.getText());
                                    params.put("paid", TEXT_PAID.getText());
                                    params.put("balance", TEXT_BALANCE.getText());
                                    params.put("paymenttype", pt.getTypename());
                                    BPos.DB.Supplier su = (BPos.DB.Supplier) ses.load(BPos.DB.Supplier.class, Integer.parseInt(idsupplier.getText()));
                                    params.put("supplier", su.getName());

                                    JasperReport jasperReport = JasperCompileManager.compileReport("Report/New_GRN.jrxml");

                                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, cnctn);

                                    JasperViewer.viewReport(jasperPrint, false);
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }

                            }
                        });
                        Clear();
                        JOptionPane.showMessageDialog(rootPane, "payment success");
                    } else {
                        Clear();
                        JOptionPane.showMessageDialog(rootPane, "payment success");
                        
                    }
                    ses.flush();
                    ses.close();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "txt....");
                }
            } else {
                JOptionPane.showConfirmDialog(rootPane, "Please add Supplier");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BTN_SAVEActionPerformed

    public void Clear() {
        jTable1.removeAll();
        TEXT_BALANCE.setText("");
        TEXT_DISCOUNT.setText("0");
        TEXT_GRAND_TOTAL.setText("");
        TEXT_PAID.setText("");
        TEXT_SUBTOTAL.setText("");
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
    }

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void BTN_DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DELETEActionPerformed
        Clear();
    }//GEN-LAST:event_BTN_DELETEActionPerformed

    private void BTN_UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_UPDATEActionPerformed
        try {
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            dt.removeRow(jTable1.getSelectedRow());
            Total_Again();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BTN_UPDATEActionPerformed

    private void DueAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DueAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DueAmountActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_DELETE;
    private javax.swing.JButton BTN_SAVE;
    private javax.swing.JButton BTN_UPDATE;
    private javax.swing.JComboBox COMBO_PAYMENT_TYPE;
    private javax.swing.JTextField DueAmount;
    private javax.swing.JTextField TEXT_BALANCE;
    private javax.swing.JTextField TEXT_DISCOUNT;
    private javax.swing.JTextField TEXT_GRAND_TOTAL;
    private javax.swing.JTextField TEXT_PAID;
    private javax.swing.JTextField TEXT_SUBTOTAL;
    private javax.swing.JLabel company;
    public javax.swing.JPanel grnPanel;
    private javax.swing.JLabel idsupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel rowcount;
    private javax.swing.JLabel sup_name;
    // End of variables declaration//GEN-END:variables

}
