/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BPos.View;

import BPos.DB.Products;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.concurrent.Executor;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author Bhagya
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Add_Customer ad;
    Add_Supplier as;
    Add_Product aPro;
    Settings set;
    Grn grn;
    Invoice in;
    Stock ss;
    int UserID;

    public Home(int id, String name, String type) {
        initComponents();
        UserID = id;
        this.jLabel4.setText(name);
        if (!type.equals("Admin")) {
            p1.setVisible(false);
            bkpanel.setVisible(false);
        }
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
//        this.setResizable(false);
        ad = new Add_Customer();
        as = new Add_Supplier();
        aPro = new Add_Product();
        set = new Settings();
        grn = new Grn();
        in = new Invoice();
        ss = new Stock();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    try {
                        DateTime.setText(new Date() + "");
                        Thread.sleep(1000);
                        System.gc();
                    } catch (InterruptedException ex) {
                    }
                }
            }
        }).start();
        loadExpire();
    }

    public void loadExpire() {
        try {

            Session ses = BPos.Connection.NewHibernateUtil.getSessionFactory().openSession();

            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Criteria cr = ses.createCriteria(BPos.DB.Stock.class);
            cr.add(Restrictions.le("exdate", df.format(new Date())));
            List<BPos.DB.Stock> l = cr.list();
            for (BPos.DB.Stock l1 : l) {
                Transaction tr1 = ses.beginTransaction();
                l1.setStatus(4);
                ses.update(l1);
                tr1.commit();
                ses.flush();
            }
            ses.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoice_Returns1 = new BPos.View.Invoice_Returns();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MainHomePanel = new javax.swing.JPanel();
        p2 = new javax.swing.JPanel();
        bkpanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        bkup2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        restore1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        p1 = new javax.swing.JPanel();
        BTN_BAK_RES = new javax.swing.JButton();
        BTN_SETTING = new javax.swing.JButton();
        slidepanel = new javax.swing.JPanel();
        supBTN = new javax.swing.JButton();
        adcus = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        AddPro = new javax.swing.JButton();
        BTN_GRN = new javax.swing.JButton();
        Invoice_BTN = new javax.swing.JButton();
        Invoice_BTN1 = new javax.swing.JButton();
        Stock_BTN = new javax.swing.JButton();
        DateTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        MainHomePanel.setBackground(new java.awt.Color(255, 255, 255));
        MainHomePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        bkpanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8jPanel3MouseExited(evt);
            }
        });

        bkup2.setBackground(new java.awt.Color(255, 255, 255));
        bkup2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        bkup2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Blue-Backup-W-icon.png"))); // NOI18N
        bkup2.setText("Backup now");
        bkup2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bkup2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bkup2bkupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bkup2bkupMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkup2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkup2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });

        restore1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        restore1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Green-Backup-icon.png"))); // NOI18N
        restore1.setText("Restore");
        restore1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restore1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restore1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(restore1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(restore1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bkpanelLayout = new javax.swing.GroupLayout(bkpanel);
        bkpanel.setLayout(bkpanelLayout);
        bkpanelLayout.setHorizontalGroup(
            bkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bkpanelLayout.setVerticalGroup(
            bkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bkpanelLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        p1.setBackground(new java.awt.Color(255, 255, 255));
        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        BTN_BAK_RES.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        BTN_BAK_RES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/backuprestore2.png"))); // NOI18N
        BTN_BAK_RES.setContentAreaFilled(false);
        BTN_BAK_RES.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/backuprestore.png"))); // NOI18N
        BTN_BAK_RES.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/backuprestore2.png"))); // NOI18N
        BTN_BAK_RES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_BAK_RESMouseClicked(evt);
            }
        });
        BTN_BAK_RES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BAK_RESActionPerformed(evt);
            }
        });

        BTN_SETTING.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        BTN_SETTING.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Settings.png"))); // NOI18N
        BTN_SETTING.setContentAreaFilled(false);
        BTN_SETTING.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Settings 2.png"))); // NOI18N
        BTN_SETTING.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Settings.png"))); // NOI18N
        BTN_SETTING.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_SETTINGMouseClicked(evt);
            }
        });
        BTN_SETTING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SETTINGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BTN_BAK_RES, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BTN_SETTING, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addComponent(BTN_BAK_RES, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BTN_SETTING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainHomePanelLayout = new javax.swing.GroupLayout(MainHomePanel);
        MainHomePanel.setLayout(MainHomePanelLayout);
        MainHomePanelLayout.setHorizontalGroup(
            MainHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainHomePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        MainHomePanelLayout.setVerticalGroup(
            MainHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainHomePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(MainHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        slidepanel.setBackground(new java.awt.Color(255, 255, 255));

        supBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/add Supplier 2.png"))); // NOI18N
        supBTN.setText("jButton1");
        supBTN.setContentAreaFilled(false);
        supBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Add Supplier.png"))); // NOI18N
        supBTN.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/add Supplier 2.png"))); // NOI18N
        supBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supBTNMouseClicked(evt);
            }
        });
        supBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supBTNActionPerformed(evt);
            }
        });

        adcus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/add customer 2.png"))); // NOI18N
        adcus.setText("jButton1");
        adcus.setContentAreaFilled(false);
        adcus.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/add customer.png"))); // NOI18N
        adcus.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/add customer 2.png"))); // NOI18N
        adcus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adcusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adcusMouseEntered(evt);
            }
        });
        adcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adcusActionPerformed(evt);
            }
        });

        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Home 2.png"))); // NOI18N
        homebtn.setText("jButton1");
        homebtn.setContentAreaFilled(false);
        homebtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Home.png"))); // NOI18N
        homebtn.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Home 2.png"))); // NOI18N
        homebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebtnMouseClicked(evt);
            }
        });
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        AddPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/addproduct_Low.png"))); // NOI18N
        AddPro.setText("jButton1");
        AddPro.setContentAreaFilled(false);
        AddPro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/addproduct_High.png"))); // NOI18N
        AddPro.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/addproduct_Low.png"))); // NOI18N
        AddPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddProMouseEntered(evt);
            }
        });
        AddPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProActionPerformed(evt);
            }
        });

        BTN_GRN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/grnlow.png"))); // NOI18N
        BTN_GRN.setText("jButton1");
        BTN_GRN.setContentAreaFilled(false);
        BTN_GRN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/grn_high.png"))); // NOI18N
        BTN_GRN.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/addproduct_Low.png"))); // NOI18N
        BTN_GRN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_GRNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTN_GRNMouseEntered(evt);
            }
        });
        BTN_GRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_GRNActionPerformed(evt);
            }
        });

        Invoice_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Invoice_Low.png"))); // NOI18N
        Invoice_BTN.setText("jButton1");
        Invoice_BTN.setContentAreaFilled(false);
        Invoice_BTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Invoice_High.png"))); // NOI18N
        Invoice_BTN.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Invoice_Low.png"))); // NOI18N
        Invoice_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invoice_BTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Invoice_BTNMouseEntered(evt);
            }
        });
        Invoice_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Invoice_BTNActionPerformed(evt);
            }
        });

        Invoice_BTN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/message.png"))); // NOI18N
        Invoice_BTN1.setContentAreaFilled(false);
        Invoice_BTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invoice_BTN1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Invoice_BTN1MouseEntered(evt);
            }
        });
        Invoice_BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Invoice_BTN1ActionPerformed(evt);
            }
        });

        Stock_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/stock.png"))); // NOI18N
        Stock_BTN.setText("jButton1");
        Stock_BTN.setContentAreaFilled(false);
        Stock_BTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/stock2.png"))); // NOI18N
        Stock_BTN.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/stock.png"))); // NOI18N
        Stock_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stock_BTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Stock_BTNMouseEntered(evt);
            }
        });
        Stock_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stock_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout slidepanelLayout = new javax.swing.GroupLayout(slidepanel);
        slidepanel.setLayout(slidepanelLayout);
        slidepanelLayout.setHorizontalGroup(
            slidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slidepanelLayout.createSequentialGroup()
                .addComponent(Invoice_BTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(slidepanelLayout.createSequentialGroup()
                .addGroup(slidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adcus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_GRN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Invoice_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stock_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        slidepanelLayout.setVerticalGroup(
            slidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slidepanelLayout.createSequentialGroup()
                .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(supBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(adcus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AddPro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BTN_GRN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Invoice_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Stock_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(Invoice_BTN1))
        );

        DateTime.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        DateTime.setForeground(new java.awt.Color(102, 153, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("User : ");

        jLabel4.setText("Bhagya Perera");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Social/Twitter%20alt%204.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Social/Facebook%20alt%201.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/Social/Google%2B%20alt.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/btn/Grn_R.png"))); // NOI18N
        jButton3.setText("GRN Returns");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/btn/Invoice_R.png"))); // NOI18N
        jButton6.setText("Invoice Return");
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BPos/Img/btn/logout_png.png"))); // NOI18N
        jButton7.setText("Logout");
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(slidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(MainHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(DateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(jButton6)
                                    .addComponent(jButton7)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(MainHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adcusActionPerformed
        try {
            MainHomePanel.removeAll();
            MainHomePanel.repaint();
            ad.addCustomerMainPanel.setSize(MainHomePanel.getSize());
            MainHomePanel.add(ad.addCustomerMainPanel);
            ad.addCustomerMainPanel.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_adcusActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed

        try {
            MainHomePanel.removeAll();
            MainHomePanel.repaint();
            MainHomePanel.add(p1);
            MainHomePanel.add(p2);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_homebtnActionPerformed

    private void homebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseClicked
        try {
            Image adp12 = ImageIO.read(getClass().getResource("/BPos/Img/grnlow.png"));
            BTN_GRN.setIcon(new ImageIcon(adp12));
            Image img = ImageIO.read(getClass().getResource("/BPos/Img/Home.png"));
            homebtn.setIcon(new ImageIcon(img));
            Image img1 = ImageIO.read(getClass().getResource("/BPos/Img/add customer 2.png"));
            adcus.setIcon(new ImageIcon(img1));
            Image supimg = ImageIO.read(getClass().getResource("/BPos/Img/Add Supplier 2.png"));
            supBTN.setIcon(new ImageIcon(supimg));
            Image adp = ImageIO.read(getClass().getResource("/BPos/Img/addproduct_Low.png"));
            AddPro.setIcon(new ImageIcon(adp));
            Image adp123 = ImageIO.read(getClass().getResource("/BPos/Img/Invoice_Low.png"));
            Invoice_BTN.setIcon(new ImageIcon(adp123));
            Image adp1234 = ImageIO.read(getClass().getResource("/BPos/Img/stock.png"));
            Stock_BTN.setIcon(new ImageIcon(adp1234));
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_homebtnMouseClicked

    private void adcusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adcusMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_adcusMouseEntered

    private void adcusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adcusMouseClicked
        // TODO add your handling code here:///////////////////////////////////////////////////
        try {
            Image img = ImageIO.read(getClass().getResource("/BPos/Img/Home 2.png"));
            homebtn.setIcon(new ImageIcon(img));
            Image img1 = ImageIO.read(getClass().getResource("/BPos/Img/add customer.png"));
            adcus.setIcon(new ImageIcon(img1));
            Image supimg = ImageIO.read(getClass().getResource("/BPos/Img/Add Supplier 2.png"));
            supBTN.setIcon(new ImageIcon(supimg));
            Image adp = ImageIO.read(getClass().getResource("/BPos/Img/addproduct_Low.png"));
            AddPro.setIcon(new ImageIcon(adp));
            Image adp12 = ImageIO.read(getClass().getResource("/BPos/Img/grnlow.png"));
            BTN_GRN.setIcon(new ImageIcon(adp12));
            Image adp123 = ImageIO.read(getClass().getResource("/BPos/Img/Invoice_Low.png"));
            Invoice_BTN.setIcon(new ImageIcon(adp123));
            Image adp1234 = ImageIO.read(getClass().getResource("/BPos/Img/stock.png"));
            Stock_BTN.setIcon(new ImageIcon(adp1234));
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_adcusMouseClicked

    private void supBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supBTNMouseClicked
        try {
            Image adp12 = ImageIO.read(getClass().getResource("/BPos/Img/grnlow.png"));
            BTN_GRN.setIcon(new ImageIcon(adp12));
            Image supimg = ImageIO.read(getClass().getResource("/BPos/Img/Add Supplier.png"));
            supBTN.setIcon(new ImageIcon(supimg));
            Image img = ImageIO.read(getClass().getResource("/BPos/Img/Home 2.png"));
            homebtn.setIcon(new ImageIcon(img));
            Image img1 = ImageIO.read(getClass().getResource("/BPos/Img/add customer 2.png"));
            adcus.setIcon(new ImageIcon(img1));
            Image adp = ImageIO.read(getClass().getResource("/BPos/Img/addproduct_Low.png"));
            AddPro.setIcon(new ImageIcon(adp));
            Image adp123 = ImageIO.read(getClass().getResource("/BPos/Img/Invoice_Low.png"));
            Invoice_BTN.setIcon(new ImageIcon(adp123));
            Image adp1234 = ImageIO.read(getClass().getResource("/BPos/Img/stock.png"));
            Stock_BTN.setIcon(new ImageIcon(adp1234));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_supBTNMouseClicked

    private void supBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supBTNActionPerformed
        try {
            MainHomePanel.removeAll();
            MainHomePanel.repaint();
            as.SupplirPanel.setSize(MainHomePanel.getSize());
            MainHomePanel.add(as.SupplirPanel);
            as.SupplirPanel.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_supBTNActionPerformed

    private void AddProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProMouseClicked
        // TODO add your handling code here:
        try {
            Image img = ImageIO.read(getClass().getResource("/BPos/Img/Home 2.png"));
            homebtn.setIcon(new ImageIcon(img));
            Image img1 = ImageIO.read(getClass().getResource("/BPos/Img/add customer 2.png"));
            adcus.setIcon(new ImageIcon(img1));
            Image supimg = ImageIO.read(getClass().getResource("/BPos/Img/Add Supplier 2.png"));
            supBTN.setIcon(new ImageIcon(supimg));
            Image adp = ImageIO.read(getClass().getResource("/BPos/Img/addproduct_High.png"));
            AddPro.setIcon(new ImageIcon(adp));
            Image adp12 = ImageIO.read(getClass().getResource("/BPos/Img/grnlow.png"));
            BTN_GRN.setIcon(new ImageIcon(adp12));
            Image adp123 = ImageIO.read(getClass().getResource("/BPos/Img/Invoice_Low.png"));
            Invoice_BTN.setIcon(new ImageIcon(adp123));
            Image adp1234 = ImageIO.read(getClass().getResource("/BPos/Img/stock.png"));
            Stock_BTN.setIcon(new ImageIcon(adp1234));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddProMouseClicked

    private void AddProMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AddProMouseEntered

    private void AddProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProActionPerformed
        try {
            MainHomePanel.removeAll();
            MainHomePanel.repaint();
            aPro.AddCusPanel.setSize(MainHomePanel.getSize());
            MainHomePanel.add(aPro.AddCusPanel);
            aPro.AddCusPanel.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddProActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int opt = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to close the Application ?", "Warning", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void BTN_SETTINGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_SETTINGMouseClicked
        try {
            Image img = ImageIO.read(getClass().getResource("/BPos/Img/backuprestore2.png"));
            BTN_BAK_RES.setIcon(new ImageIcon(img));
            Image img1 = ImageIO.read(getClass().getResource("/BPos/Img/Settings 2.png.png"));
            BTN_BAK_RES.setIcon(new ImageIcon(img1));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BTN_SETTINGMouseClicked

    private void BTN_SETTINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SETTINGActionPerformed
        try {
            p2.removeAll();
            p2.repaint();
            set.LoadReturns();
            set.updateStock();
            set.SettingPanel.setSize(p2.getSize());
            p2.add(set.SettingPanel);
            set.LoadSReturns();
            set.LoadCUSDebit();
            set.loadDiscount();
            set._LoadGRN();
            set.LoadInvoice();
            set.Load_SUPLIER_Debit();
            set.SettingPanel.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BTN_SETTINGActionPerformed

    private void BTN_BAK_RESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BAK_RESActionPerformed
        try {
            p2.removeAll();
            p2.repaint();
            p2.add(bkpanel);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BTN_BAK_RESActionPerformed

    private void restore1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restore1MouseEntered
        restore1.setForeground(new Color(161, 198, 249));
        restore1.setToolTipText("Restore Database");
        jPanel7.setBorder(BorderFactory.createLineBorder(new Color(161, 198, 249)));
    }//GEN-LAST:event_restore1MouseEntered

    private void restore1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restore1MouseExited
        restore1.setForeground(Color.BLACK);
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_restore1MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseExited

    private void bkup2bkupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkup2bkupMouseEntered
        bkup2.setForeground(new Color(161, 198, 249));
        bkup2.setToolTipText("Backup Database");
        jPanel8.setBorder(BorderFactory.createLineBorder(new Color(161, 198, 249)));
    }//GEN-LAST:event_bkup2bkupMouseEntered

    private void bkup2bkupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkup2bkupMouseExited
        bkup2.setForeground(Color.BLACK);
        jPanel8.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_bkup2bkupMouseExited

    private void jPanel8jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8jPanel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8jPanel3MouseEntered

    private void jPanel8jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8jPanel3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8jPanel3MouseExited

    private void BTN_BAK_RESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_BAK_RESMouseClicked
        try {
            Image img = ImageIO.read(getClass().getResource("/BPos/Img/backuprestore.png"));
            BTN_BAK_RES.setIcon(new ImageIcon(img));
            Image img1 = ImageIO.read(getClass().getResource("/BPos/Img/Settings.png.png"));
            BTN_BAK_RES.setIcon(new ImageIcon(img1));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BTN_BAK_RESMouseClicked

    private void BTN_GRNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_GRNMouseClicked
        try {
            Image img = ImageIO.read(getClass().getResource("/BPos/Img/Home 2.png"));
            homebtn.setIcon(new ImageIcon(img));
            Image img1 = ImageIO.read(getClass().getResource("/BPos/Img/add customer 2.png"));
            adcus.setIcon(new ImageIcon(img1));
            Image supimg = ImageIO.read(getClass().getResource("/BPos/Img/Add Supplier 2.png"));
            supBTN.setIcon(new ImageIcon(supimg));
            Image adp = ImageIO.read(getClass().getResource("/BPos/Img/addproduct_Low.png"));
            AddPro.setIcon(new ImageIcon(adp));
            Image adp12 = ImageIO.read(getClass().getResource("/BPos/Img/grn_high.png"));
            BTN_GRN.setIcon(new ImageIcon(adp12));
            Image adp123 = ImageIO.read(getClass().getResource("/BPos/Img/Invoice_Low.png"));
            Invoice_BTN.setIcon(new ImageIcon(adp123));
            Image adp1234 = ImageIO.read(getClass().getResource("/BPos/Img/stock.png"));
            Stock_BTN.setIcon(new ImageIcon(adp1234));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BTN_GRNMouseClicked

    private void BTN_GRNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_GRNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_GRNMouseEntered

    private void BTN_GRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GRNActionPerformed
        MainHomePanel.removeAll();
        MainHomePanel.repaint();
        grn.grnPanel.setSize(MainHomePanel.getSize());
        MainHomePanel.add(grn.grnPanel);
        grn.grnPanel.setVisible(true);
    }//GEN-LAST:event_BTN_GRNActionPerformed

    private void Invoice_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invoice_BTNMouseClicked
        try {
            Image img = ImageIO.read(getClass().getResource("/BPos/Img/Home 2.png"));
            homebtn.setIcon(new ImageIcon(img));
            Image img1 = ImageIO.read(getClass().getResource("/BPos/Img/add customer 2.png"));
            adcus.setIcon(new ImageIcon(img1));
            Image supimg = ImageIO.read(getClass().getResource("/BPos/Img/Add Supplier 2.png"));
            supBTN.setIcon(new ImageIcon(supimg));
            Image adp = ImageIO.read(getClass().getResource("/BPos/Img/addproduct_Low.png"));
            AddPro.setIcon(new ImageIcon(adp));
            Image adp12 = ImageIO.read(getClass().getResource("/BPos/Img/grnlow.png"));
            BTN_GRN.setIcon(new ImageIcon(adp12));
            Image adp123 = ImageIO.read(getClass().getResource("/BPos/Img/Invoice_High.png"));
            Invoice_BTN.setIcon(new ImageIcon(adp123));
            Image adp1234 = ImageIO.read(getClass().getResource("/BPos/Img/stock.png"));
            Stock_BTN.setIcon(new ImageIcon(adp1234));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Invoice_BTNMouseClicked

    private void Invoice_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invoice_BTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Invoice_BTNMouseEntered

    private void Invoice_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Invoice_BTNActionPerformed
        MainHomePanel.removeAll();
        MainHomePanel.repaint();
        in.InvoicePanel.setSize(MainHomePanel.getSize());
        MainHomePanel.add(in.InvoicePanel);
        in.InvoicePanel.setVisible(true);
    }//GEN-LAST:event_Invoice_BTNActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if (evt.getClickCount() > 0) {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                try {
                    URI uri = new URI("https://www.facebook.com/Bhagyaperera123");
                    desktop.browse(uri);
                } catch (IOException ex) {
                    ex.printStackTrace();
                } catch (URISyntaxException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if (evt.getClickCount() > 0) {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                try {
                    URI uri = new URI("https://plus.google.com/u/0/+bhagyaperera12345");
                    desktop.browse(uri);
                } catch (IOException ex) {
                    ex.printStackTrace();
                } catch (URISyntaxException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void Invoice_BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Invoice_BTN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Invoice_BTN1ActionPerformed

    private void Invoice_BTN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invoice_BTN1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Invoice_BTN1MouseEntered

    private void Invoice_BTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invoice_BTN1MouseClicked
        new ExpireProduct().setVisible(true);
    }//GEN-LAST:event_Invoice_BTN1MouseClicked

    private void Stock_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_BTNMouseClicked
        try {
            Image img = ImageIO.read(getClass().getResource("/BPos/Img/Home 2.png"));
            homebtn.setIcon(new ImageIcon(img));
            Image img1 = ImageIO.read(getClass().getResource("/BPos/Img/add customer 2.png"));
            adcus.setIcon(new ImageIcon(img1));
            Image supimg = ImageIO.read(getClass().getResource("/BPos/Img/Add Supplier 2.png"));
            supBTN.setIcon(new ImageIcon(supimg));
            Image adp = ImageIO.read(getClass().getResource("/BPos/Img/addproduct_Low.png"));
            AddPro.setIcon(new ImageIcon(adp));
            Image adp12 = ImageIO.read(getClass().getResource("/BPos/Img/grnlow.png"));
            BTN_GRN.setIcon(new ImageIcon(adp12));
            Image adp123 = ImageIO.read(getClass().getResource("/BPos/Img/Invoice_Low.png"));
            Invoice_BTN.setIcon(new ImageIcon(adp123));
            Image adp1234 = ImageIO.read(getClass().getResource("/BPos/Img/stock2.png"));
            Stock_BTN.setIcon(new ImageIcon(adp1234));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Stock_BTNMouseClicked

    private void Stock_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_BTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Stock_BTNMouseEntered

    private void Stock_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stock_BTNActionPerformed
        MainHomePanel.removeAll();
        MainHomePanel.repaint();
        ss.Stock_MainPanel.setSize(MainHomePanel.getSize());
        MainHomePanel.add(ss.Stock_MainPanel);
        ss.Loadstock();
        ss.Stock_MainPanel.setVisible(true);
    }//GEN-LAST:event_Stock_BTNActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new Invoice_Returns().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new GRN_Returns().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if (evt.getClickCount() > 0) {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                try {
                    URI uri = new URI("https://twitter.com/MB_Perera");
                    desktop.browse(uri);
                } catch (IOException ex) {
                    ex.printStackTrace();
                } catch (URISyntaxException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void bkup2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkup2MouseClicked
        bup();
    }//GEN-LAST:event_bkup2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPro;
    private javax.swing.JButton BTN_BAK_RES;
    private javax.swing.JButton BTN_GRN;
    private javax.swing.JButton BTN_SETTING;
    private javax.swing.JLabel DateTime;
    private javax.swing.JButton Invoice_BTN;
    private javax.swing.JButton Invoice_BTN1;
    private javax.swing.JPanel MainHomePanel;
    private javax.swing.JButton Stock_BTN;
    private javax.swing.JButton adcus;
    private javax.swing.JPanel bkpanel;
    private javax.swing.JLabel bkup2;
    private javax.swing.JButton homebtn;
    private BPos.View.Invoice_Returns invoice_Returns1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JLabel restore1;
    private javax.swing.JPanel slidepanel;
    private javax.swing.JButton supBTN;
    // End of variables declaration//GEN-END:variables

public static void bup(){
  FileOutputStream fop = null;
        BPos.Model.Backup b = new BPos.Model.Backup();
        try {
            byte[] data = b.getData("localhost", "3306", "root", "bhagya", "b_pos").getBytes();
            File filedst = new File("Backup/" + "b_pos" + ".sql");
            FileOutputStream dest = new FileOutputStream(filedst);
            dest.write(data);
            dest.flush();
            dest.close();
            JOptionPane.showMessageDialog(null, "Back Up Successfully!", "Database BackUp Wizard", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Back Up Failed." + "\n" + "For Database: ", "Database BackUp Wizard", JOptionPane.INFORMATION_MESSAGE);
            ex.printStackTrace();
        }
}

}
