/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BPos.View;

import BPos.DB.CRetunItems;
import BPos.DB.CReturns;
import BPos.DB.SReturnItems;
import BPos.DB.SReturns;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author Bhagya
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    }

    int _GrnItemID, _ProductID, _GrnID;
    double _Qty;
    String _ProName;
    GRN_Returns _GrnReturn;
    double _Available;

    public Update(int grnid, int proid, double qty, String pnm, GRN_Returns grnr, int grnID, double available) {
        initComponents();
        _GrnItemID = grnid;
        _ProductID = proid;
        _Qty = qty;
        _ProName = pnm;
        _GrnReturn = grnr;
        _GrnID = grnID;
        _Available = available;
        Avai.setText(_Available + "");
        Proid1.setText(_ProductID + "");
        Proname.setText(_ProName);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Proid1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reson = new javax.swing.JTextArea();
        rqty1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Proname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Avai = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("ID Product");

        Proid1.setEditable(false);

        jLabel5.setText("Return Quantity :");

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        reson.setColumns(20);
        reson.setRows(5);
        jScrollPane1.setViewportView(reson);

        rqty1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rqty1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rqty1KeyTyped(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Return Items");

        Proname.setEditable(false);

        jLabel8.setText("Pro Name : ");

        jLabel7.setText("Reson :");

        Avai.setEditable(false);

        jLabel9.setText("Available :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(266, 266, 266))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Avai)
                            .addComponent(Proname, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(Proid1)
                            .addComponent(rqty1))))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Proid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Proname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Avai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rqty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (!rqty1.getText().equals("")) {
                if (!reson.getText().equals("")) {
                    double d = Double.parseDouble(rqty1.getText());
                    if (!(_Qty < d)) {
                        Session ses = BPos.Connection.NewHibernateUtil.getSessionFactory().openSession();

                        BPos.DB.Products _pro = (BPos.DB.Products) ses.load(BPos.DB.Products.class, _ProductID);
                        BPos.DB.GrnItem _GrnItm = (BPos.DB.GrnItem) ses.load(BPos.DB.GrnItem.class, _GrnItemID);
                        BPos.DB.Grn _Grn = (BPos.DB.Grn) ses.load(BPos.DB.Grn.class, _GrnID);
                        // System.out.println("GRN ID :- "+_Grn.getGrnId());
                        Transaction tr = ses.beginTransaction();

                        BPos.DB.SReturns sr = new SReturns();
                        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                        String date1 = sdf1.format(new Date());
                        sr.setDateTime(date1);
                        sr.setGrn(_Grn);

                        BPos.DB.SReturnItems sri = new SReturnItems();
                        sri.setProducts(_pro);
                        sri.setSReturns(sr);
                        sri.setQty(Double.parseDouble(rqty1.getText()));
                        sri.setReson(reson.getText());
            
                  

                        BPos.DB.Stock s = _GrnItm.getStock();
                        
                        s.setQty(s.getQty() - Double.parseDouble(rqty1.getText()));
                        ses.save(sr);
                        ses.save(sri);
                        ses.update(s);
                        tr.commit();
                        JOptionPane.showMessageDialog(rootPane, "Return Success!!");
                        ses.close();
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Long Qty");
                        rqty1.setForeground(Color.red);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Reson Empty");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Qty Empty");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rqty1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rqty1KeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0' && c <= '9') || (c == '.' && !rqty1.getText().contains(".")))) {
            evt.consume();
        }
    }//GEN-LAST:event_rqty1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rqty1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rqty1KeyReleased

        if (!Avai.getText().equals("")) {
            if (!rqty1.getText().equals("")) {
                double av = Double.parseDouble(Avai.getText());
                double re = Double.parseDouble(rqty1.getText());

                if (av < re) {
                    rqty1.setForeground(Color.red);
                    jButton2.setEnabled(false);
                } else {
                    rqty1.setForeground(Color.BLACK);
                   jButton2.setEnabled(true);
                }
            }
        }


    }//GEN-LAST:event_rqty1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Avai;
    private javax.swing.JTextField Proid1;
    private javax.swing.JTextField Proname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea reson;
    private javax.swing.JTextField rqty1;
    // End of variables declaration//GEN-END:variables
}
